#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_60_ansi(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSLS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSPC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_UP, KC_CAPS, KC_LGUI, KC_LALT, KC_SPC, MO(1), KC_LEFT, KC_DOWN, KC_RGHT),
	[1] = LAYOUT_60_ansi(KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS, KC_HOME, KC_MPRV, KC_MPLY, KC_MNXT, KC_DEL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, BL_TOGG, BL_DOWN, BL_UP, KC_TRNS, KC_PGDN, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_VOLD, KC_VOLU)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    static uint8_t mod_state;

    // Capture the current state of modifiers
    mod_state = get_mods();

    switch (keycode) {
        case KC_H:
            if ((mod_state & MOD_BIT(KC_LALT)) && record->event.pressed) {
                unregister_mods(MOD_BIT(KC_LALT));  // Temporarily unregister Left Alt
                tap_code(KC_LEFT);  // Send Left Arrow key
                set_mods(mod_state);  // Re-register Left Alt
                return false;  // Skip further processing of this key event
            }
            break;
        case KC_J:
            if ((mod_state & MOD_BIT(KC_LALT)) && record->event.pressed) {
                unregister_mods(MOD_BIT(KC_LALT));
                tap_code(KC_DOWN);
                set_mods(mod_state);
                return false;
            }
            break;
        case KC_K:
            if ((mod_state & MOD_BIT(KC_LALT)) && record->event.pressed) {
                unregister_mods(MOD_BIT(KC_LALT));
                tap_code(KC_UP);
                set_mods(mod_state);
                return false;
            }
            break;
        case KC_L:
            if ((mod_state & MOD_BIT(KC_LALT)) && record->event.pressed) {
                unregister_mods(MOD_BIT(KC_LALT));
                tap_code(KC_RGHT);
                set_mods(mod_state);
                return false;
            }
            break;
        case KC_SCLN: // ';' key
            if ((mod_state & (MOD_BIT(KC_LALT) | MOD_BIT(KC_LCTL))) == (MOD_BIT(KC_LALT) | MOD_BIT(KC_LCTL)) && record->event.pressed) {
                tap_code16(KC_WBAK); // Send Browser Back
                return false;
            }
            break;
        case KC_QUOT: // '\'' key
            if ((mod_state & (MOD_BIT(KC_LALT) | MOD_BIT(KC_LCTL))) == (MOD_BIT(KC_LALT) | MOD_BIT(KC_LCTL)) && record->event.pressed) {
                tap_code16(KC_WFWD); // Send Browser Forward
                return false;
            }
            break;
    }
    return true;  // Process all other keycodes normally
}
